### PR TITLE
try add prettier-eslint support for prettier_d

### PR DESCRIPTION
**Pull request by clijiac**
use --usePrettierEslint will try to use prettier-eslint lib to format instead of prettier.

### CODE REVIEW

**Comment by clijiac** [comment]
close for some issue

**Comment by clijiac** [comment]
fixed for prettier-eslint

**Comment by josephfrazier** [comment]
Hey @clijiac, thanks for putting the effort into this, but I'm still not sure it's a good idea.

Couldn't you just add [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier) and [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier) to your `.eslintrc`, then use `eslint_d` instead of `prettier_d`?. This would probably be better than the other workaround in https://github.com/josephfrazier/prettier_d/issues/2#issuecomment-308858753, which requires both `prettier_d` and `eslint_d`.

**Comment by clijiac** [comment]
him that way seems good, I will have a try.

**Pull request closed without merging**
